### ISSUE TITLE
Energy issues in 1.14.4

### ISSUE THREAD

**Issue by XiaoYiUce** [TheBusyBiscuit/Slimefun4#1011]
Description (Required)
EnergyNet java.util.ConcurrentModificationException

Server Log
Slimefun Data:
ID: ENERGY_REGULATOR
Inventory: false
Data: {"id":"ENERGY_REGULATOR"}

Stacktrace:

java.lang.NullPointerException
at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:147)
at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$49.tick(SlimefunSetup.java:3022)
at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:191)
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

Evidence / Proof (Required)
ENERGY_REGULATOR dissapear

Environment (Required)
CS-CoreLib v1.5.18
Slimefun 4.1.15
git-Paper-166 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by TheBusyBiscuit** [comment]
Your Slimefun and CS-CoreLib Versions do not support 1.14 ....
