### ISSUE TITLE
WorldGuard issue

### ISSUE THREAD

**Issue by RussianAdmin** [TheBusyBiscuit/Slimefun4#1056]
I use WorldGuard version 6.2.2 and when installing any version of CS Corelib - WorldGuard gives this error. Changing the WG version is useless; this is the only stable version for 1.12.2. I tried to install earlier versions of CS Corelib - the problem did not resolve. Help!

[CS-CoreLib] Task #18 for CS-CoreLib vv1.6.1 generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at me.mrCookieSlime.CSCoreLibPlugin.protection.modules.WorldGuardProtectionModule.<clinit>(WorldGuardProtectionModule.java:18) ~[?:?]
        at me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionManager.<init>(ProtectionManager.java:37) ~[?:?]
        at me.mrCookieSlime.CSCoreLibPlugin.CSCoreLib$2.run(CSCoreLib.java:115) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot.jar:git-Paper-1574]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[PaperSpigot.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[PaperSpigot.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[PaperSpigot.jar:git-Paper-1574]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[PaperSpigot.jar:git-Paper-1574]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[PaperSpigot.jar:git-Paper-1574]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PaperSpigot.jar:git-Paper-1574]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]

 - Minecraft Version: Paper 1.12.2
 - Slimefun Version: 4.1.15
 - CS-CoreLib Version: 1.6.1

**Comment by TheBusyBiscuit** [comment]
This is Slimefun's Issue Tracker, not CS-CoreLib...
