### ISSUE TITLE
Smeltery not reacting when fence is clicked

### ISSUE THREAD

**Issue by ice4ed** [TheBusyBiscuit/Slimefun4#1130]
## Description (Required)

Prior issue of #1129  fixed the dispenser not working when it was right-clicked as part of the Smeltery Multi-Block (thank you). Now items can be placed into the multi-block and it appears the multi-block still registers but there is still no reaction to clicking the fence.

## Steps to reproduce the Issue (Required)

1. Build Smeltery Multi-Block
2. Place in Iron Dust (Optional)
3. Right-Click Fence
4. No Response

## Expected behavior (Required)

A product of smelted iron dust to appear in the dispenser. If there is no iron dust in the machine I would expect the recipe not recognized message.

## Server Log / Error Report

No errors show up when clicking anything on the multi-block. I can still forward a log but it does not show any errors that would define what the issue would be.

## Environment (Required)

-  Minecraft Version: Minecraft 1.14.4
-  Minecraft Server Jar: CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4)
-  Slimefun Version: Slimefun4 - #267
-  CS-CoreLib Version: CS-CoreLib - #76

**Comment by JordyWeerwag1994** [comment]
[16:17:49 ERROR]: Could not pass event PlayerInteractEvent to Slimefun vDEV - 266 (git 0f488c14)
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Dispenser
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.multiblocks.Smeltery.onInteract(Smeltery.java:47) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.multiblocks.MultiBlockMachine.lambda$getInteractionHandler$0(MultiBlockMachine.java:57) ~[?:?]
        at me.mrCookieSlime.Slimefun.listeners.BlockListener.onRightClick(BlockListener.java:91) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor83.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-196]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923) ~[patched_1.14.4.jar:git-Paper-196]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

i get this dont know if its because of that tho but the smeltery doent work and cant open the dispenser at all.

and a minut ago it did crash

**Comment by Exstii** [comment]
Yup having the exact same issue, appreciate you throwing this post here cause we were so confused aha

**Comment by mrcoffee1026** [comment]
You can also leave smeltery empty and attempt a click then, it doesn't give a "recipe not recognized" error either.

**Comment by Exstii** [comment]
Well users on my server have now mentioned that it is working.

**Comment by mrcoffee1026** [comment]
Then is it only broken for paper?
