### ISSUE TITLE
Spam error on ItemUseEvent

### ISSUE THREAD

**Issue by FabioZumbi12** [TheBusyBiscuit/Slimefun4#1179]
## Description (Required)

Spams errors on console infinitelly about ItemUseevent and dont need player interactions to spam that.

## Steps to reproduce the Issue (Required)

Just started after the update to 299. Dont know what causes, players is not using item at the momento of the spam.

## Server Log / Error Report

Edit: Found the complete error, who will help to fix
```
[16:04:24] [Server thread/ERROR]: Could not pass event ItemUseEvent to Slimefun vDEV - 299 (git a2fe40cf)
java.lang.NullPointerException: null
	at me.mrCookieSlime.Slimefun.api.Slimefun.isEnabled(Slimefun.java:211) ~[?:?]
	at me.mrCookieSlime.Slimefun.api.Slimefun.hasUnlocked(Slimefun.java:153) ~[?:?]
	at me.mrCookieSlime.Slimefun.listeners.ItemListener.onRightClick(ItemListener.java:230) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor270.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-213]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-213]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-213]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-213]
	at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.ItemUseListener.onRightClick(ItemUseListener.java:22) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor230.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-213]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-213]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-213]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-213]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-213]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-213]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
![image](https://user-images.githubusercontent.com/5833818/66726257-a3688680-ee0e-11e9-9b99-0d9833b2e9bb.png)

## Environment (Required)

![image](https://user-images.githubusercontent.com/5833818/66726289-cb57ea00-ee0e-11e9-8ce4-db6223140a28.png)

**Comment by WalshyDev** [comment]
Update

**Comment by FabioZumbi12** [comment]
I've updated, but instead this error, al players cant break blocks, open chests and do nothing on world! Only on build 301 the players can play normally. The bug starts from +302!

**Comment by creator3** [comment]
Vanilla items now fall through to the final `else e.setCancelled(true);`
I'm not exactly sure exactly what that case is supposed to handle, but I can confirm that replacing it with `else if (slimefunItem != null) e.setCancelled(true);`  fixes the issue. There may be a cleaner solution, but I'm afraid to break anything (case in point: this)
