### ISSUE TITLE
Able to obtain the "credits" bookandquill item

### ISSUE THREAD

**Issue by RoboMWM** [TheBusyBiscuit/Slimefun4#153]
## Description
Finally figured out where you're displaying the stats you download every 20 minutes, lol.

Turns out, when you click said book, the book is droppable, and is able to be picked up.

It seems that the issue resolves itself on restart, so perhaps it has something to do with that web connector while the server runs?

## Server Log
```
[Server thread/ERROR]: Could not pass event InventoryClickEvent to CS-CoreLib v1.5.12
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1059]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1059]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1059]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1059]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1059]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1889) ~[patched_1.11.2.jar:git-Paper-1059]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.11.2.jar:git-Paper-1059]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.11.2.jar:git-Paper-1059]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1059]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_71]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1059]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1059]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1059]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1059]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1059]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 63
	at java.util.Arrays$ArrayList.set(Unknown Source) ~[?:1.8.0_71]
	at net.minecraft.server.v1_11_R1.NonNullList.set(SourceFile:47) ~[patched_1.11.2.jar:git-Paper-1059]
	at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107) ~[patched_1.11.2.jar:git-Paper-1059]
	at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInventory.setItem(CraftInventory.java:88) ~[patched_1.11.2.jar:git-Paper-1059]
	at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.setup(ChestMenu.java:208) ~[?:?]
	at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.open(ChestMenu.java:240) ~[?:?]
	at me.mrCookieSlime.Slimefun.SlimefunGuide.openCredits(SlimefunGuide.java:326) ~[?:?]
	at me.mrCookieSlime.Slimefun.SlimefunGuide$8.onClick(SlimefunGuide.java:198) ~[?:?]
	at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.MenuClickListener.onClick(MenuClickListener.java:33) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1139.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1059]
	... 16 more
```

If you really think you need to see the full server log, you can, though it's just me testing experience calculations beforehand. https://gist.github.com/RoboMWM/d1db7868467fa9b8b42123c42d8d180c

## Evidence / Proof
http://i.imgur.com/jQEvfsq.gifv
http://i.imgur.com/2cQIFUX.png
http://i.imgur.com/yGKHkeG.png

## Environment
CS-CoreLib 1.5.12
Slimefun 4.1.2
Paper version git-Paper-1059 (MC: 1.11.2)

**Comment by TheBusyBiscuit** [comment]
This has already been fixed...

**Comment by RoboMWM** [comment]
It was? All I can find is a related issue: #144 which indicated or referenced nothing other than the typical close-and-lock. Commits don't seem to indicate any fixing of such either, nor any commits related to SlimefunGuide's class.
