### ISSUE TITLE
Missing file: data-storage\Slimefun\stored-chunks\chunks.sfc

### ISSUE THREAD

**Issue by TerminatorNL** [TheBusyBiscuit/Slimefun4#154]
When using the `stop` command, this stacktrace occurs:

```
[21:13:53 WARN]: java.io.FileNotFoundException: data-storage\Slimefun\stored-chunks\chunks.sfc (Het systeem kan het opgegeven pad niet vinden)
[21:13:53 WARN]: 	at java.io.FileInputStream.open0(Native Method)
[21:13:53 WARN]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[21:13:53 WARN]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[21:13:53 WARN]: 	at me.mrCookieSlime.Slimefun.SlimefunStartup.onDisable(SlimefunStartup.java:484)
[21:13:53 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[21:13:53 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[21:13:53 WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[21:13:53 WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[21:13:53 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345)
[21:13:53 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464)
[21:13:53 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612)
[21:13:53 WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

Context: I'm writing an addon for the slimefun plugin (AMAZING API, btw), and I removed the world folders and the data-storage folder and the slimefun and CSCoreLib configuration folders

Steps to reproduce:
1: type `stop` in the server console

Full server log: [latest.txt](https://github.com/TheBusyBiscuit/Slimefun4/files/788430/latest.txt)

Versions:
`CS-CoreLib v1.5.12` and `Slimefun v4.1.2.jar`

**Comment by Joapple** [comment]
Always stop the server BEFORE removing thoses files, it tries to write it in, but since you deleted it, they are no longer in there. If you check the config, it says do not edit while the server is running, you can't say they didn't prevent you :P

**Comment by TerminatorNL** [comment]
I _did_ stop the server accordingly.

And while it was off i removed the said files

**Comment by TerminatorNL** [comment]
More context:

I was doing a world reset so:

I stopped the server
I deleted the world folders
I deleted the data-storage folder
I deleted /plugins/CSCoreLib
I deleted /plugins/Slimefun

Started server normally
Stop server normally

The said error occurs.

Did i miss anything? Because all OTHER storage files generate normally
