### ISSUE TITLE
SlimeFun not saving blocks?

### ISSUE THREAD

**Issue by TheWranger** [TheBusyBiscuit/Slimefun4#177]
## Description
Upon disabling SlimeFun/Stopping the server I get a save error from slimefun and it doesn't seem to save any blocks from the nether or the end.

## Server Log
Full server log- http://pastebin.com/yAmA43ZX

## Evidence / Proof
Unable to find any evidence or proof other than the logs.

## Environment
Running Minecraft 1.11.2, CS-Corelib v1.5.13, Slimefun v4.1.2
Spigot version-
CraftBukkit version git-Spigot-7d78b81-775f1e1 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by TerminatorNL** [comment]
I suspect this:

`[21:53:47] [Server thread/WARN]: java.io.FileNotFoundException: data-storage/Slimefun/stored-chunks/chunks.sfc (No such file or directory)
[21:53:47] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[21:53:47] [Server thread/WARN]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[21:53:47] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[21:53:47] [Server thread/WARN]: 	at me.mrCookieSlime.Slimefun.SlimefunStartup.onDisable(SlimefunStartup.java:484)
[21:53:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[21:53:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[21:53:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[21:53:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[21:53:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345)
[21:53:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:462)
[21:53:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:610)
[21:53:47] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)`

Might be the issue. I've seen a simular log myself: https://github.com/TheBusyBiscuit/Slimefun4/issues/154

**Comment by Deathinflames** [comment]
Hello, We are experiencing the same message on server stop.

`[08:19:52] [Server thread/INFO]: [Slimefun] Disabling Slimefun v4.1.2
[08:19:52] [Server thread/WARN]: java.io.FileNotFoundException: data-storage/Slimefun/stored-chunks/chunks.sfc (No such file or directory)
[08:19:52] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[08:19:52] [Server thread/WARN]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[08:19:52] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[08:19:52] [Server thread/WARN]: 	at me.mrCookieSlime.Slimefun.SlimefunStartup.onDisable(SlimefunStartup.java:484)
[08:19:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[08:19:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[08:19:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[08:19:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[08:19:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345)
[08:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464)
[08:19:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612)
[08:19:52] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)`
