### ISSUE TITLE
SeismicAxeListener error when disabled and sheep eat grass

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#1806]
## Description (Required)

SeismicAxeListener error when disabled and sheep eat grass

## Steps to reproduce the Issue (Required)

1. Disable Seismic Axe
2. Summon sheeps
3. Flood this error when sheep eat the grass.

## Expected behavior (Required)

No flood this error.

## Server Log / Error Report

```
[17:02:40] [Server thread/ERROR]: Could not pass event EntityChangeBlockEvent to Slimefun vDEV - 479 (git 5842598f)
java.lang.NullPointerException: null
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SeismicAxeListener.onBlockFall(SeismicAxeListener.java:32) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor222.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-183]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1158) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PathfinderGoalEatTile.e(PathfinderGoalEatTile.java:73) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:149) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.EntityInsentient.doTick(EntityInsentient.java:686) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2596) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.EntityAgeable.movementTick(EntityAgeable.java:171) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.EntityAnimal.movementTick(EntityAnimal.java:28) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.EntitySheep.movementTick(EntitySheep.java:86) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:794) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.World.a(World.java:862) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:516) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1272) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1133) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:941) ~[patched_1.15.2.jar:git-Paper-183]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Environment (Required)

 - Minecraft Version: 1.15.2
 - Slimefun Version: vDEV - 479 (git 5842598f)
 - CS-CoreLib Version: vDEV - 83 (git 8081bb4f)

**Comment by andris155** [comment]
Same error on all EntityChangeBlockEvent

**Comment by andris155** [comment]
Thanks
