### ISSUE TITLE
Research disable not work

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#1807]
## Description (Required)

Research disable not work

## Steps to reproduce the Issue (Required)

1. Start server and generate default config files.
2. Open Researches.yml.
3. Set one research enabled: true to false
4. Restart server.
5. The Slimefun writes this when server is starting: An Error occured while initializing Slimefun Researches for Slimefun DEV - 480 (git 6dd02aaf)

## Expected behavior (Required)

Research disable works

## Server Log / Error Report

```
[19:53:31] [Server thread/INFO]: [Slimefun] Loading researches...
[19:53:31] [Server thread/ERROR]: [Slimefun] An Error occured while initializing Slimefun Researches for Slimefun DEV - 480 (git 6dd02aaf)
java.util.ConcurrentModificationException: null
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970) ~[?:?]
	at java.util.LinkedList$ListItr.remove(LinkedList.java:925) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.Research.register(Research.java:246) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.setup.ResearchSetup.register(ResearchSetup.java:274) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.setup.ResearchSetup.setupResearches(ResearchSetup.java:84) ~[?:?]
	at me.mrCookieSlime.Slimefun.SlimefunPlugin.loadResearches(SlimefunPlugin.java:431) ~[?:?]
	at me.mrCookieSlime.Slimefun.SlimefunPlugin.onEnable(SlimefunPlugin.java:187) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:487) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:891) ~[patched_1.15.2.jar:git-Paper-183]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Environment (Required)

 - Minecraft Version: 1.15.2
 - Slimefun Version: vDEV - 480 (git 6dd02aaf)
 - CS-CoreLib Version: vDEV - 83 (git 8081bb4f)

**Comment by andris155** [comment]
Thanks!

**Comment by weyaj** [comment]
nem adtam ra engedelyt h torold a kommentem gecukam
