### ISSUE TITLE
An ItemSetting was invoked but was not initialized yet (Solar Helmet)

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#1813]
## Description (Required)

An ItemSetting was invoked but was not initialized yet (Solar Helmet)
I use the default items.yml.

## Steps to reproduce the Issue (Required)

1. Start server with default Slimefun items.yml (generated by Slimefun vDEV - 481)
2. Write the /sf cheat command and search to the Solar Helmet
3. Pick up the Solar Helmet.

## Expected behavior (Required)

No write this error.

## Server Log / Error Report

```
[23:44:51 WARN]: [Slimefun] Plugin Slimefun vDEV - 481 (git 5115175d) generated an exception while executing task 12
java.lang.IllegalArgumentException: An ItemSetting was invoked but was not initialized yet.
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.15.2.jar:git-Paper-183]
        at io.github.thebusybiscuit.slimefun4.api.items.ItemSetting.getValue(ItemSetting.java:88) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.electric.gadgets.SolarHelmet.getChargeAmount(SolarHelmet.java:22) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.ArmorTask.checkForSolarHelmet(ArmorTask.java:100) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.ArmorTask.lambda$run$0(ArmorTask.java:60) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.api.player.PlayerProfile.get(PlayerProfile.java:305) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.ArmorTask.run(ArmorTask.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-183]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-183]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Environment (Required)

 - Minecraft Version: 1.15.2
 - Slimefun Version: vDEV - 481 (git 5115175d)
 - CS-CoreLib Version: vDEV - 83 (git 8081bb4f)

**Comment by andris155** [comment]
Thanks
