### ISSUE TITLE
Could Not find the Stored Chunks file

### ISSUE THREAD

**Issue by Goldentoenail** [TheBusyBiscuit/Slimefun4#205]
## Description
New Server creation Spigot 1.11.2. Log error on shutdown

## Server Log
```
[14:29:02] [Server thread/INFO]: [Slimefun] Disabling Slimefun v4.1.3
[14:29:02] [Server thread/WARN]: java.io.FileNotFoundException: data-storage\Slimefun\stored-chunks\chunks.sfc (The system cannot find the file specified)
[14:29:02] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[14:29:02] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[14:29:02] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[14:29:02] [Server thread/WARN]: 	at me.mrCookieSlime.Slimefun.SlimefunStartup.onDisable(SlimefunStartup.java:500)
[14:29:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[14:29:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[14:29:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[14:29:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[14:29:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345)
[14:29:02] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464)
[14:29:02] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612)
[14:29:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:29:02] [Server thread/INFO]: [CS-CoreLib] Disabling CS-CoreLib v1.5.13
```

## Evidence / Proof
Log file only
New server, new world, never played on by another player.

## Environment
Spigot 1.11.2 (Freshly built)
CS-CoreLib v1.5.13
Slimefun v4.1.3
SlimefunLuckyBlocks_v1.1
ExoticGarden_v1.6.1

**Comment by John000708** [comment]
Is the server running on a Linux or on a Windows instance?
