### ISSUE TITLE
Plugin disable error with PlaceholderAPI 2.10.7

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#2145]
## Description (REQUIRED)

Plugin disable error with PlaceholderAPI 2.10.7

## Steps to reproduce the Issue (REQUIRED)

1. Start server with Slimefun and PlaceholderAPI 2.10.7 plugin.
2. Stop server.

## Expected behavior (REQUIRED)

No write this error.

## Error Reports

```
[17:20:31] [Server thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.7
[17:20:31] [Server thread/ERROR]: Error occurred while disabling PlaceholderAPI v2.10.7 (Is it up to date?)
java.lang.NullPointerException: null
	at io.github.thebusybiscuit.slimefun4.core.services.plugins.PlaceholderAPIHook.getAuthor(PlaceholderAPIHook.java:19) ~[?:?]
	at me.clip.placeholderapi.expansion.PlaceholderExpansion.hashCode(PlaceholderExpansion.java:260) ~[?:?]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:?]
	at java.util.HashMap.put(HashMap.java:607) ~[?:?]
	at java.util.HashSet.add(HashSet.java:220) ~[?:?]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:352) ~[?:?]
	at java.util.HashSet.<init>(HashSet.java:120) ~[?:?]
	at com.google.common.collect.Sets.newHashSet(Sets.java:273) ~[patched_1.16.1.jar:git-Paper-93]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.unregisterAll(LocalExpansionManager.java:327) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.kill(LocalExpansionManager.java:92) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPIPlugin.onDisable(PlaceholderAPIPlugin.java:114) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.disablePlugins(CraftServer.java:434) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:774) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1047) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-93]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.1
 - Slimefun Version:  Slimefun vDEV - 602 (git 5a1b868c)
 - CS-CoreLib Version: CS-CoreLib vDEV - 90 (git 9dd4a1cf)

**Comment by WalshyDev** [comment]
Apparently SF isn't loaded or the plugin.yml doesn't have authors. 

You using a modified jar? Got a full log?

**Comment by andris155** [comment]
https://pastebin.com/dN3GaCz9

**Comment by WalshyDev** [comment]
Ok this is during disable. Slimefun just disabled before PlaceholderAPI. I consider this a non issue. It causes no actual issue and is not something we can really do anything about.

**Comment by TheBusyBiscuit** [comment]
Could just make the author hardcoded XD

**Comment by andris155** [comment]
If I modify the author: The Slimefun 4 Community -> author: [The Slimefun 4 Community] in plugin.yml file PlaceholderAPI no writes this error.

**Comment by WalshyDev** [comment]
True, but still, not sure why they even do this

**Comment by andris155** [comment]
Thanks
