### ISSUE TITLE
Plugin writes warn in console if I give the same waypoint name twice

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#2209]
## Description (REQUIRED)

Plugin writes warn in console if I give the same waypoint name twice.

## Steps to reproduce the Issue (REQUIRED)

1. Place GPS Marker Tool
2. Type test.
3. Place GPS Marker Tool
4. Type test.

## Expected behavior (REQUIRED)

Plugin do not writes warn in console if I give the same waypoint name twice.

## Error Reports

```
[23:00:44 WARN]: [Slimefun] Task #23406 for Slimefun vDEV - 627 (git 7de9dd66) generated an exception
java.lang.IllegalArgumentException: A Waypoint with that id already exists for this Player
        at io.github.thebusybiscuit.slimefun4.api.player.PlayerProfile.addWaypoint(PlayerProfile.java:233) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.api.gps.GPSNetwork.lambda$null$8(GPSNetwork.java:286) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.1
 - Slimefun Version: vDEV - 627 (git 7de9dd66)
 - CS-CoreLib Version: vDEV - 90 (git 9dd4a1cf)

**Comment by andris155** [comment]
Thanks
