### ISSUE TITLE
WorldEdit

### ISSUE THREAD

**Issue by Mgazul** [TheBusyBiscuit/Slimefun4#283]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1096.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit.jar:?]
	... 35 more
Caused by: java.lang.IllegalAccessError: me/mrCookieSlime/Slimefun/WorldEdit/WESlimefunManager$1
	at me.mrCookieSlime.Slimefun.WorldEdit.WESlimefunManager.wrapForLogging(WESlimefunManager.java:24) ~[Slimefun.jar:?]
	at sun.reflect.GeneratedMethodAccessor1096.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit.jar:?]
	... 35 more

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
