### ISSUE TITLE
Paperclip Build Not Loading...

### ISSUE THREAD

**Issue by crston** [TheBusyBiscuit/Slimefun4#284]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.

When I opened the server with spigot build, the server stopped frequently, so I changed to paperbuild but it disappeared, but the slimefun function was disabled.
## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
[21:19:37 ERROR]: Error occurred while disabling Slimefun v4.1.8 (Is it up to date?)
java.lang.NullPointerException
        at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:59) ~[?:?]
        at me.mrCookieSlime.Slimefun.SlimefunStartup.onDisable(SlimefunStartup.java:400) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1095]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) ~[patched_1.11.2.jar:git-Paper-1095]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) ~[patched_1.11.2.jar:git-Paper-1095]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) ~[patched_1.11.2.jar:git-Paper-1095]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.11.2.jar:git-Paper-1095]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.11.2.jar:git-Paper-1095]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1393) ~[patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1198) ~[patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1095]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1095]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1095]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[21:19:37 INFO]: [Slimefun] Loading Files...
## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

Lastest Version.

**Comment by TheBusyBiscuit** [comment]
Locked & Closed.<br><br>Please read our Community Guidelines before posting an Issue on this Repository.<br>https://github.com/TheBusyBiscuit/Slimefun4/blob/master/.github/CONTRIBUTING.md
