### ISSUE TITLE
Energy Regulators disappearing.

### ISSUE THREAD

**Issue by DryCryCrystal** [TheBusyBiscuit/Slimefun4#338]
## Description
I am not good with indirect describing so I put it all in the video.

## Server Log
https://pastebin.com/rYLc9Z7S

I could not get the full log as it was too big, trimmed it down a bit, only removed repeating text.

## Evidence / Proof
https://youtu.be/D83pyu9tHHE

## Environment
CS-CoreLib 1.5.14
Slimefun 4.1.7

Addons:
SlimefunOres 1.4.6
Barrels 1.9
SlimefunGuidePlus 1.0
SlimeXpansion 1.1.8

**Comment by TheBusyBiscuit** [comment]
When Blocks disappear, they leave an Error Report in /plugins/Slimefun/

**Comment by DryCryCrystal** [comment]
Server Software: CraftBukkit
  Build: git-Spigot-72c2605-251a5b6 (MC: 1.10.2)
  Minecraft: 1.10.2-R0.1-SNAPSHOT

Installed Plugins (14)
  + CoreProtect 2.13.1
  + dynmap 2.4-1148
  + WorldEdit 6.1.5;4651611
  + Essentials 2.0.1-b488
  + WhitelistGUI 1.0
  + SimpleRename 9.7
  + CS-CoreLib 1.5.14
  + CustomJoin 0.9
  + Gapples 0.3
  + Slimefun 4.1.7
  + SlimefunOres 1.4.6
  + Barrels 1.9
  + SlimefunGuidePlus 1.0
  + SlimeXpansion 1.1.8

Ticked Block:
  World: APTERRA
  X: -1999
  Y: 52
  Z: 607

Slimefun Data:
  ID: ENERGY_REGULATOR
  Inventory: false
  Data: {"id":"ENERGY_REGULATOR"}

Stacktrace:

java.lang.IllegalArgumentException: Item cannot be null
	at org.apache.commons.lang.Validate.noNullElements(Validate.java:364)
	at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventory.addItem(CraftInventory.java:274)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.machines.ReactorAccessPort.pushItems(ReactorAccessPort.java:223)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AReactor$10.generateEnergy(AReactor.java:372)
	at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:102)
	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$47.tick(SlimefunSetup.java:3100)
	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:204)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Poslovitch** [comment]
Maybe related to #162 ?
