### ISSUE TITLE
Asynchronous Async Chunk Load! Blocking thread until it returns 

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#343]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Randomly write plugin this error on the console.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
If need please write comment!

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
```
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:51)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:174)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:606)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at org.bukkit.Location.getBlock(Location.java:86)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$50.generateEnergy(SlimefunSetup.java:3180)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:102)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$47.tick(SlimefunSetup.java:3111)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:204)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:31:10] [Craft Scheduler Thread - 1984/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
Paper v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9
Installed Addons (4)
ExtraGear v1.1.1
SlimefunLuckyBlocks v1.1
ExoticGarden v1.6.3
ElectricSpawners v1.0
```

**Comment by TheBusyBiscuit** [comment]
By all means of logic, this Error is impossible to be thrown.
https://github.com/TheBusyBiscuit/Slimefun4/blob/master/src/me/mrCookieSlime/Slimefun/Setup/SlimefunSetup.java#L3179
