### ISSUE TITLE
Could not pass event EntityDamageEvent to Slimefun v4.1.9

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#368]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Could not pass event EntityDamageEvent to Slimefun v4.1.9

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
Send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
```
[13:09:47] [Server thread/ERROR]: Could not pass event EntityDamageEvent to Slimefun v4.1.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1147]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:566) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1360) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:853) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:880) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:603) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityLiving.e(EntityLiving.java:1225) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityHuman.e(EntityHuman.java:1511) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.Block.fallOn(Block.java:536) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.Entity.a(Entity.java:1062) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:190) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:770) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:681) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1147]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1147]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1147]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: x not finite
	at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:115) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.util.Vector.checkFinite(Vector.java:624) ~[patched_1.12.jar:git-Paper-1147]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.setVelocity(CraftEntity.java:242) ~[patched_1.12.jar:git-Paper-1147]
	at me.mrCookieSlime.Slimefun.listeners.ArmorListener.onDamage(ArmorListener.java:58) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor622.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1147]
	... 31 more
```

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
Paper v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9
Installed Addons (4)
ExtraGear v1.1.1
SlimefunLuckyBlocks v1.1
ExoticGarden v1.6.3
ElectricSpawners v1.0
```

**Comment by DaddyElf** [comment]
I am running Slimefun v4.1.9 on git-Spigot-5340a52-963b19c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT) and I am getting the same error. I recreated the error by using a fire aspect II sword to kill a skeleton.
