### ISSUE TITLE
ProgrammableAndroid error

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#486]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
```
Server Software: Paper
  Build: git-Paper-1233 (MC: 1.12.2)
  Minecraft: 1.12.2-R0.1-SNAPSHOT

Installed Plugins (83)
  + Vehicles 8.6
  + ClearInvConfirmation 1.1.0
  + PlugMan 2.1.4
  + PlayerWarp [v1.1 release]
  + NametagEdit 4.1.7
  + MineMarket-Universal 2.94
  + EntityDetection 1.0 (build #12)
  + Murder 10.1
  + ViaVersion 1.3.0
  + Stats 1.0.0
  + ViaBackwards 2.3.1
  + icJukeBox 1.6.4
  + CoreProtect 2.14.2
  + LuckPerms 3.4.15
  + MineMarketAPI 1.0
  + OpenInv 3.2.1
  + CreativeNbtControl 1.9
  + XrayInformer 3.6.0
  + NoSpawnerChange 1.7
  + Heads 1.12.1
  + WorldBorder 1.8.7
  + Votifier 2.3.5
  + ProtocolLib 4.3.0
  + OpenTerrainGenerator 1.12 v7
  + VotingPlugin 5.10.5
  + FastAsyncWorldEdit 17.09.22-b8aaeb0-907-16.6.4
  + RedstoneClockDetector 0.2.7-b12
  + TimeIsMoney 1.9.6.1
  + ConditionalCommands 1.4
  + Lottery 1.1.1
  + Kredites 1.0.0
  + mcMMO 1.5.09-SNAPSHOT
  + CS-CoreLib 1.5.16
  + Vault 1.6.1
  + FastAsyncVoxelSniper 17.09.22-b8aaeb0-907-16.6.4
  + AuctionHouse 3.3
  + VoxelSniper 5.171.0-SNAPSHOT
  + MyCommand 5.3.4
  + WorldEdit 6.1.8-SNAPSHOT;cd4729f
  + Essentials 2.0.1-b530
  + CompatNoCheatPlus 6.6.4-RC-sMD5NET-b88
  + GameBox 1.5.9
  + SafeTrade 1.0.15
  + Battleship 2.3.3
  + NoCheatPlus 3.15.2-SNAPSHOT-sMD5NET-b1113
  + GemCrush 2.3.1
  + EssentialsChat 2.0.1-b530
  + Sudoku 1.1.1
  + PartyChatSpy 1.2
  + CookieClicker 1.1.1
  + PlotSquared 17.10.23-097159d-1924
  + WorldGuard 6.2.2-SNAPSHOT;1708-3a8e3e8
  + Minesweeper 2.3.1
  + WhacAMole 1.0.2
  + Slimefun 4.1.11
  + LockettePro 2.9.0
  + myZone 1.1.170
  + EssentialsGeoIP 2.0.1-b530
  + RandomTeleport 1.7.4 (build #20)
  + ConnectFour 1.2.1
  + PvPManager 3.7.5
  + EssentialsSpawn 2.0.1-b530
  + TitleManager 2.0.9
  + ExtraGear 1.1.1
  + RestrictedCreative 1.10.1
  + 2048 1.3.1
  + Multiverse-Core 2.5.0-b727
  + Shopkeepers 1.83
  + SlimefunLuckyBlocks 1.1
  + ExoticGarden 1.6.3
  + CraftBook 3.9-SNAPSHOT-jenkins-CraftBook-187
  + ChestShop 3.8.13-SNAPSHOT (build #33)
  + ElectricSpawners 1.0
  + MobArena 0.98.1
  + ExtraHeads 1.0
  + SkinsRestorer 13.1.4
  + Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714
  + LimitedCreative 2.3-SNAPSHOT-256f165622
  + AreaShop 2.4.0
  + ChatControl 7.6.2
  + SurvivalGames Beta 1.9.5
  + Paintball 1.3.9
  + MyPet 2.3.7

Ticked Block:
  World: world
  X: -2161
  Y: 64
  Z: 2972

Slimefun Data:
  ID: PROGRAMMABLE_ANDROID_2_FISHERMAN
  Inventory: false
  Data: null

Stacktrace:

java.lang.NullPointerException
	at me.mrCookieSlime.Slimefun.Android.ProgrammableAndroid.tick(ProgrammableAndroid.java:233)
	at me.mrCookieSlime.Slimefun.Android.ProgrammableAndroid$33.tick(ProgrammableAndroid.java:1462)
	at me.mrCookieSlime.Slimefun.api.TickerTask$1.run(TickerTask.java:92)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
	at java.lang.Thread.run(Thread.java:748)
```

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
01.11 16:07:45 [Server] INFO Paper v1_12_R1
01.11 16:07:45 [Server] INFO CS-CoreLib v1.5.16
01.11 16:07:45 [Server] INFO Slimefun v4.1.11
01.11 16:07:45 [Server] INFO Installed Addons (5)
01.11 16:07:45 [Server] INFO ExtraGear v1.1.1
01.11 16:07:45 [Server] INFO SlimefunLuckyBlocks v1.1
01.11 16:07:45 [Server] INFO ExoticGarden v1.6.3
01.11 16:07:45 [Server] INFO ElectricSpawners v1.0
01.11 16:07:45 [Server] INFO ExtraHeads v1.0
```

**Comment by Poslovitch** [comment]
NPE caused at line 233 from ProgrammableAndroid.java : ``if (BlockStorage.getBlockInfo(b, "paused").equals("false")) {``
Corresponding to the error report : 
```Slimefun Data:
  ID: PROGRAMMABLE_ANDROID_2_FISHERMAN
  Inventory: false
  Data: null

The data of this android is ``null``. Needs investigation to see if this is a normal behaviour (to have a null data) and then add a null-check, or if this should never happen and then investigate the causes of this null data.

**Comment by Poslovitch** [comment]
Here is another error report (i cut useless data).

```
Server Software: Paper
  Build: git-Paper-"e5e5063" (MC: 1.12.2)
  Minecraft: 1.12.2-R0.1-SNAPSHOT

Slimefun Data:
  ID: PROGRAMMABLE_ANDROID_2_FARMER
  Inventory: false
  Data: null

Stacktrace:

java.lang.NullPointerException
	at me.mrCookieSlime.Slimefun.Android.ProgrammableAndroid.tick(ProgrammableAndroid.java:233)
	at me.mrCookieSlime.Slimefun.Android.ProgrammableAndroid$33.tick(ProgrammableAndroid.java:1462)
	at me.mrCookieSlime.Slimefun.api.TickerTask$1.run(TickerTask.java:92)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
	at java.lang.Thread.run(Thread.java:748)
```

It was thrown when an ExoticGarden plant grew where the Android was.
I'll push a fix in EG asap.
