### ISSUE TITLE
Error executing task 106

### ISSUE THREAD

**Issue by viocu** [TheBusyBiscuit/Slimefun4#487]
## Description
Console throwing this error:

`11/06/2017 01:25:23

01:25:23

[Slimefun] Plugin Slimefun v4.1.11 generated an exception while executing task 106

Console
 
11/06/2017 01:25:23

01:25:23

java.lang.IllegalStateException: Asynchronous entity track!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:82) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.World.b(World.java:1095) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1160) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1125) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.Chunk.addEntities(Chunk.java:753) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:131) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:573) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.Location.getChunk(Location.java:82) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at me.mrCookieSlime.Slimefun.api.BlockStorage.refreshCache(BlockStorage.java:483) ~[?:?]
at me.mrCookieSlime.Slimefun.api.BlockStorage.setBlockInfo(BlockStorage.java:389) ~[?:?]
at me.mrCookieSlime.Slimefun.api.BlockStorage.setBlockInfo(BlockStorage.java:367) ~[?:?]
at me.mrCookieSlime.Slimefun.api.BlockStorage.setBlockInfo(BlockStorage.java:355) ~[?:?]
at me.mrCookieSlime.Slimefun.api.BlockStorage._integrated_moveBlockInfo(BlockStorage.java:445) ~[?:?]
at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:330) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

I just installed MythicMobs last night and I haven't seen this error before installing that. 

## Server Log

pastebin: https://pastebin.com/PfeLTSUR

## Evidence / Proof
Doesn't APPEAR to be affecting anything in game that I can tell, but it is being very spammy in console. 

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

CraftBukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.11
Installed Addons (4)
ExoticGarden v1.6.3
HotbarPets v1.1
SlimefunLuckyBlocks v1.1
SensibleToolbox v1.1

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/365

**Comment by meiamsome** [comment]
This looks related to #509 to me as it's a similar base reason, looks like the BlockStorage could use some updates to primarily use Location rather than Block.
