### ISSUE TITLE
Asynchronous Async Chunk Load! Blocking thread until it returns (Paper)

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/Slimefun4#488]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Asynchronous Async Chunk Load! Blocking thread until it returns (Paper)

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
I send if need.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
```
[13:34:34] [Craft Scheduler Thread - 844/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:51)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:174)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:606)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at org.bukkit.Location.getBlock(Location.java:91)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$51.generateEnergy(SlimefunSetup.java:3204)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:102)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$47.tick(SlimefunSetup.java:3114)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:204)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:34:34] [Craft Scheduler Thread - 844/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
```
08.11 16:50:09 [Server] INFO Paper v1_12_R1
08.11 16:50:09 [Server] INFO CS-CoreLib v1.5.16
08.11 16:50:09 [Server] INFO Slimefun v4.1.11
08.11 16:50:09 [Server] INFO Installed Addons (5)
08.11 16:50:09 [Server] INFO ExtraGear v1.1.1
08.11 16:50:09 [Server] INFO SlimefunLuckyBlocks v1.1
08.11 16:50:09 [Server] INFO ExoticGarden v1.6.3
08.11 16:50:09 [Server] INFO ElectricSpawners v1.0
08.11 16:50:09 [Server] INFO ExtraHeads v1.0
```

**Comment by TheBusyBiscuit** [comment]
This should not happen, I'll just say it's because of Paper, because it works fine with other Server Software.
