### ISSUE TITLE
CargoNet.matchesFilter() creates a lot of lag

### ISSUE THREAD

**Issue by krusic22** [TheBusyBiscuit/Slimefun4#514]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
CargoNet.matchesFilter() creates a lot of lag...

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

Might not be directly connected!

`java.lang.IllegalStateException:
Asynchronous Async Chunk Load! Blocking thread until it returns 
at net.minecraft.server.v1_11_R1.MCUtil.ensureMain(MCUtil.java:51)
at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:174)
at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:606)
at org.bukkit.Location.getBlock(Location.java:87)
at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$50.generateEnergy(SlimefunSetup.java:3181)
at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:102)
at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$47.tick(SlimefunSetup.java:3112)
at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:204)
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)`

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
![image](https://user-images.githubusercontent.com/8352435/33438390-f6123e0a-d5ea-11e7-8dc8-b68867180a5d.png)

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

**Spigot version 1.11.2**
Also tried Paper, Taco, Torch, Bukkit none helped.
![image](https://user-images.githubusercontent.com/8352435/33439384-9739d7fa-d5ed-11e7-97a8-914745b5109a.png)

**Comment by andris155** [comment]
Same problem (Paper 1.12.2)

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/421

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/488

**Comment by Poslovitch** [comment]
Cargo is currently over-optimized with the current way it is working right now.

Someone may find a more optimized way to work for Cargos, but this would imply a big rewrite. And, as far as I know, this "someone" doesn't contribute yet ^^

**Comment by WindUnwaken** [comment]
Transportpipe on spigot have similar feature ,but it doesn't support slimefun, maybe take a look, and get some idea to optimize cargo network
