### ISSUE TITLE
Android mining interface glitch

### ISSUE THREAD

**Issue by Mee8a** [TheBusyBiscuit/Slimefun4#553]
## Description
When a mining android breaks an android interface, instead of breaking the block and storing it as an interface, it reset's it back to a standard dispenser.

For example, place an android interface below a miner and use the android miner to break the interface, it will drop a dispenser rather than an interface.

## Server Log
N/A

## Environment
Slimefun v4.1.11
Minecraft V1.12.1 (We are running ViaVersion on a bungeecord network)
CS-CoreLib V 1.5.15

**Comment by Poslovitch** [comment]
This bug might happen for every Slimefun block.
Needs some testing.

Can you please provide a video as an evidence for this bug?

**Comment by Mee8a** [comment]
Yeah ill get someone to record this glitch for me

**Comment by Redemption198** [comment]
@Poslovitch As you said this bug happens with many Slimefun blocks, in fact, they return vanilla blocks.
I've tested a few blocks:

Did it break?

ANCIENT_PEDESTAL Yes
NETHER_DRILL Yes
GPS_TELEPORTER_MATRIX Yes
GPS_ACTIVATION_DEVICE_SHARED Yes
GPS_ACTIVATION_DEVICE_PERSONAL Yes
ELEVATOR_PLATE Yes
SOLAR_GENERATOR Yes
ARMOR_FORGE Yes
COMPRESSOR Yes
ORE_CRUSHER Yes
BLOCK_PLACER Yes

GPS_TELEPORTER_PYLON No
REINFORCED_SPAWER No

They all returned vanilla blocks (Skeleton skulls in case of custom skulls).

**Comment by Redemption198** [comment]
@Poslovitch I've tried this workaround and it seems to be working but has some bugs (for example it causes the bug reported on https://github.com/TheBusyBiscuit/Slimefun4/pull/549 ), more tests needed:

![test](https://user-images.githubusercontent.com/25185835/34426005-59002114-ec32-11e7-8aac-4a0ee56cfcf2.PNG)

**Comment by Poslovitch** [comment]
Then it might be caused by a mishandled block break event. I should have a look

**Comment by Redemption198** [comment]
@Poslovitch I've tried to fix this problem (the code is at my fork), but the bug reappears when the miner's inventory is full, and the block's type that is in front of the miner is equal to one of the blocks which are in the inventory, the block breaks (even if it shouldn't) but returns a vanilla block.

I'll make an example, here's the situtation: 
![2018-01-03_16 37 14](https://user-images.githubusercontent.com/25185835/34527029-788176f2-f0a4-11e7-9467-dfb9f63d102d.png)

This is the miner's inventory (five stacks of grass blocks, one dispenser):
![2018-01-03_16 37 17](https://user-images.githubusercontent.com/25185835/34527052-8f204b72-f0a4-11e7-8e97-d4e4c7539c43.png)

The script is (START, MOVE & DIG FORWARD, REPEAT).

When the script starts, for the first time it recognizes the block as a Slimefun block, at the second time it enters in the else clause because the variable item is null, I don't know why it happens, shouldn't it contains always the block?

**Comment by Redemption198** [comment]
Another graphical bug, when miner moves, nearby entities like dropped items or armor stands disappears, but they are still there, in fact, they'll reappear if the player goes away from that chunk and returns.

**Comment by Poslovitch** [comment]
> When the script starts, for the first time it recognizes the block as a Slimefun block, at the second time it enters in the else clause because the variable item is null, I don't know why it happens, shouldn't the variable contains always the block?

Get the Slimefun debug fish (/sf debug_fish, you have to be OP in order to use it) and right click the Dispenser to see if the data is still there.

> the bug reappears when the miner's inventory is full (no more slots available), and the block's type that is in front of the miner is equal to one of the blocks which are in the inventory, the block breaks (even if it shouldn't) but returns a vanilla block.

Didn't check all your code, but does the Miner android checks what is the block it wants to mine, then checks if it can fit (InvUtils#fits(), afaik) in its inventory? Maybe this method can be the cause, because it comes from CS-CL.

I'm sorry I can't help you. Due to the Eleanor Storm which litterally wiped out everything in France yesterday, my internet box is off, and the mobile internet network is nearly dying.

**Comment by Redemption198** [comment]
The problem is exactly when the miner checks what is the block it wants to mine, the first tick is correct and it doesn't do anything, the other ticks go always in the else clause because of BlockStorage.check(block) which seems to return null, even if the block is a Slimefun block. I'll look at fits(), i tried using the one from CS-CL but it doesn't solve, I'll try to fix.

**Comment by Poslovitch** [comment]
Did you do the checks with the debug_fish as I suggested you?
Right clicking the dispenser before launching the script to see the "sample" data, then right-click again and again until no data appears.
If BlockStorage returns null, this means that somehow the block has been removed from it. And therefore, no data should appear when right-clicking the block using the debug-fish

**Comment by Redemption198** [comment]
@Poslovitch yes there are no data with the debug_fish after the miner starts its script, seems that BlockStorage removes block's information even if it shouldn't.

Yes, I've Discord but my spoken English is bad.

**Comment by Poslovitch** [comment]
Okay, then what's your Discord ID ? Your english is not a problem :)

So, about the removal of the info from the BlockStorage... Something might go wrong in the breaking condition. Does it explicitly remove the data from the BlockStorage?

**Comment by Redemption198** [comment]
@Poslovitch did some more testing with debug_fish, and I got an EventException while clicking on it

This is the chat output, as you can see is half way printed:
![2018-01-06_01 10 10](https://user-images.githubusercontent.com/25185835/34633836-17c4677a-f27f-11e7-86e9-8ebd896c54a0.png)


This is the error printed by the console:
`
[01:05:11 ERROR]: Could not pass event PlayerInteractEvent to Slimefun v4.1.12
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja                                                                  va:306) ~[spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav                                                                  a:62) ~[spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j                                                                  ava:500) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j                                                                  ava:485) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInt                                                                  eractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40                                                                  c9ef]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractM                                                                  anager.java:458) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav                                                                  a:951) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseIt                                                                  em.java:37) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseIt                                                                  em.java:1) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:                                                                  13) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [                                                                  ?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.                                                                  12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:                                                                  748) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:                                                                  406) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:                                                                  679) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav                                                                  a:577) [spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at me.mrCookieSlime.Slimefun.listeners.ItemListener.debug(ItemListener.j                                                                  ava:121) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1                                                                  .8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja                                                                  va:302) ~[spigot-1.12.2.jar:git-Spigot-bb614f8-e40c9ef]
        ... 17 more
`

This is miner's inventory (x1 Ancient Pedestal, x1 Android Interface Fuel, x1 Android Interface Items. x1 Block Placer, x1 Grind Stone, x64 Sand):
![2018-01-06_01 16 58](https://user-images.githubusercontent.com/25185835/34633873-60b42010-f27f-11e7-8351-04435fd09733.png)
The block in front of the miner used to be an Electric Furnace, now it's just a furnace with a custom name (no output if clicked with debug_fish).

Still not sure what could be the cause.

My Discord ID is Redemption#2351 by the way.

**Comment by Poslovitch** [comment]
Hmmm... This proves my *theory*.

You can edit your previous message to remove your Discord ID by the way. I've sent you a friend request.
