### ISSUE TITLE
Exception caught while ticking a Block:java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Arein669** [TheBusyBiscuit/Slimefun4#576]
Server Software: CraftBukkit
  Build: git-Spigot-549c1fa-45c8386 (MC: 1.12.2)
  Minecraft: 1.12.2-R0.1-SNAPSHOT

Installed Plugins (94)
  + Bookshelves 1.2.0
  + PW 0.5
  + Questioner 0.6
  + HPFixer 1.1
  + UltimateAnnounce 1.5
  + GroupManager 2.0.1-b332
  + AntiAFKPlus 2.11
  + PlugMan 2.1.4
  + BetterChairs 0.9.5
  + NametagEdit 4.2.0
  + FarmLimiter 1.2
  + DeluxeTags 1.7.1
  + DropPartyCYT 0.3.0
  + StreamUtils 1.0-SNAPSHOT
  + Tablist 1.3.2.9
  + CoreProtect 2.14.2
  + Wild 3.9.3
  + RealPing 0.5.0
  + FirstJoinPlus 2.4.1
  + GhostFix 1.0
  + Essentials TeamCity
  + NoLagg 1.2
  + PVPFix 1.0
  + AutoSmelt 1.3
  + BuycraftX 10.3.1
  + GemsToBlocks 2.0
  + Votifier 2.3.5
  + ActionHealth 3.2.0
  + IronElevators 1.1
  + LRestart 0.0.1
  + ProtocolLib 4.3.0
  + Multiverse-Core 2.5.0-b727
  + NightVision 1.0
  + GuiRedeemMCMMO 1.5.4
  + Giveall 1.1.0
  + SignEdit 1.7.0
  + FastAsyncWorldEdit 18.01.11-0a127df-967-18.1.8
  - iDisguise 5.6.4
  + RedstoneClockDetector 0.2.5
  + ImageOnMap 2.99
  + ColoredMotd 1.4.3
  + EssentialsChat TeamCity
  + AlwaysOnline 6.1
  + FeatherBoard 3.23.0
  + CommandWatcher 2.0
  + mcMMO 1.5.09-SNAPSHOT
  + CS-CoreLib 1.5.16
  + StaffChat 2.3
  + Multiverse-Portals 2.5.0-b751
  + Vault 1.5.6-b49
  + GAListener 1.4.5
  + SimpleRename 10.0
  + LWC 1.9.4
  + HolographicDisplays 2.2.6
  + DailyBonus 2.2.3.2
  + VoteParty 1.11.0
  + Marriage 2.0.17
  + AuctionHouse 3.3
  + ChatItem 1.3.6.2
  + EssentialsGeoIP TeamCity
  + PlayerVaults 3.6.0-SNAPSHOT-b209
  + EssentialsSpawn TeamCity
  + WorldEdit 6.1.7;dd00bb1
  + CombatLog 2.3.0
  + EZRanksLite v1.6
  + BountyHunters 1.4.1c
  + LiteBans 2.2.4
  + BlockCommandTab 2.0.3
  + TreasureChest 8.4.5
  + Citizens 2.0.22-SNAPSHOT (build 1487)
  + MythicDrops 4.1.2-bd6c06f
  + SuperVanish 5.10.1
  + WorldGuard 6.2.1;84bc322
  + Slimefun 4.1.13
  + MythicMobs 4.3.2-SNAPSHOT
  + PrisonCells 2.3
  + Duels 2.2.3
  + Barrels 1.11
  + CommandNPC 1.9.1
  + CustomEnchantments 2.4c
  + SlimeXpansion 1.1.9
  + Towny 0.92.0.1
  + Jobs 4.2.1
  + CrateReloaded 1.3.98.3
  + SilkSpawners 5.0.0
  + TownyChat 0.47
  + Plan 4.1.4
  + ExoticGarden 1.6.3
  + ChestShop 3.8.13-SNAPSHOT (build #31)
  + NoFlyZone 1.3
  + Quests 3.0.0-Naomi-b${env.BUILD_NUMBER}
  + TownyNameUpdater 1.0
  + ShopGUIPlus 1.12.0
  + AWD 2.3.2

Ticked Block:
  World: world
  X: 110707
  Y: 58
  Z: 92157

Slimefun Data:
  ID: REDSTONE_RECEIVER
  Inventory: false
  Data: {"id":"REDSTONE_RECEIVER","transmitterLoc":"world;110726;49;92147"}

Stacktrace:

java.lang.IllegalStateException: Asynchronous entity track!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:108)
	at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:90)
	at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21)
	at net.minecraft.server.v1_12_R1.World.b(World.java:1093)
	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1160)
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1125)
	at net.minecraft.server.v1_12_R1.Chunk.addEntities(Chunk.java:753)
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:138)
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:95)
	at me.john000708.SlimeXpansion$10.tick(SlimeXpansion.java:261)
	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:222)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

https://pastebin.com/raw/sxBHvpRa

**Comment by TheBusyBiscuit** [comment]
This is not an Error from Slimefun.
It's from SlimeXpansion, post it there, not here.
