### ISSUE TITLE
Issues Running Slimefun

### ISSUE THREAD

**Issue by invaderxyz** [TheBusyBiscuit/Slimefun4#678]
## Description
The server loads Slimefun, as stated in the console.
The players can get the Slimefun Guidebook. They can't open it. When they try to, this error appears.
The players have every Slimefun permission except for _Slimefun.cheat*_ and should be able to open the book. They reportedly find, they can not do anything else Slimefun related.

## Server Log
```
Server] ERROR Could not pass event ItemUseEvent to Slimefun vDEV
[Server] INFO org.bukkit.event.EventException: null
[Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.ItemUseListener.onRightClick(ItemUseListener.java:23) [CS-CoreLib%20v1.5.16.jar:?]
[Server] INFO at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[?:?]
[Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
[Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
[Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:989) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
[Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
[Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot_1.12.2.jar:git-Spigot-7754231-94b0980]
[Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[Server] INFO Caused by: java.lang.NoSuchMethodError: me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.setEmptySlotsClickable(Z)Lme/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu;
```

## Environment
Minecraft/Spigot 1.12.2
Slimefun #37 
CSCoreLib v1.5.18

**Comment by VoidAngel** [comment]
You simply need to update CSCoreLib ;D

**Comment by invaderxyz** [comment]
Huh, I thought I did... 
Well, that fixed it. Thanks!
