### ISSUE TITLE
mrCookieSlime.Slimefun warn

### ISSUE THREAD

**Issue by TimingsFix** [TheBusyBiscuit/Slimefun4#682]
me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$52.generateEnergy(SlimefunSetup.java:3263)
[15:30:24 WARN]: at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:102)
[15:30:24 WARN]: at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$47.tick(SlimefunSetup.java:3152)
[15:30:24 WARN]: at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:200)
[15:30:24 WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[15:30:24 WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[15:30:24 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:30:24 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:30:24 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:30:24 WARN]: at java.lang.Thread.run(Thread.java:748)
[15:30:24 INFO]: The_Legacy was blown up by The_Legacy
[15:30:24 WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:606)
[15:30:24 WARN]: at org.bukkit.Location.getBlock(Location.java:87)
[15:30:24 WARN]: at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$52.generateEnergy(SlimefunSetup.java:3263)
[15:30:24 WARN]: at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:102)
[15:30:24 WARN]: at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$47.tick(SlimefunSetup.java:3152)
[15:30:24 WARN]: at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:200)
[15:30:24 WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)

**Comment by TheBusyBiscuit** [comment]
Blocking you now for spam.
