### ISSUE TITLE
Slimefun Error Server

### ISSUE THREAD

**Issue by Gumist** [TheBusyBiscuit/Slimefun4#701]
[17:04:37] [Server thread/ERROR]: Could not pass event ItemUseEvent to Slimefun vv4.1.15
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.ItemUseListener.onRightClick(ItemUseListener.java:23) [CS-CoreLib%20v1.5.16.jar:?]
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:982) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.setEmptySlotsClickable(Z)Lme/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu;
	at me.mrCookieSlime.Slimefun.SlimefunGuide.openMainMenu(SlimefunGuide.java:498) ~[?:?]
	at me.mrCookieSlime.Slimefun.SlimefunGuide.openGuide(SlimefunGuide.java:343) ~[?:?]
	at me.mrCookieSlime.Slimefun.listeners.ItemListener.onRightClick(ItemListener.java:175) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
	... 26 more

**Comment by TheBusyBiscuit** [comment]
Update CS-CoreLib...
