### ISSUE TITLE
input pipe node not running

### ISSUE THREAD

**Issue by crston** [TheBusyBiscuit/Slimefun4#775]
## Description (Required)
Describe your Issue AS DETAILED AS POSSIBLE.
not running input pipe
## Server Log
All Error files/messages need to be provided via http://pastebin.com/
[01:05:24 ERROR]: Could not pass event ItemUseEvent to Slimefun vDEV
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.ItemUseListener.onRightClick(ItemUseListener.java:23) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1240) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at me.mrCookieSlime.CSCoreLibPlugin.protection.modules.WorldGuardProtectionModule.canAccessChest(WorldGuardProtectionModule.java:19) ~[?:?]
        at me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionManager.canAccessChest(ProtectionManager.java:106) ~[?:?]
        at me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionManager.canAccessChest(ProtectionManager.java:82) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.machines.CargoInputNode$1.canOpen(CargoInputNode.java:210) ~[?:?]
        at me.mrCookieSlime.Slimefun.api.inventory.BlockMenu.canOpen(BlockMenu.java:109) ~[?:?]
        at me.mrCookieSlime.Slimefun.listeners.ItemListener.onRightClick(ItemListener.java:252) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-b620c21-19d654b]
        ... 25 more
>11
## Evidence / Proof (Required)
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

## Environment (Required)
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

DEV 1.13 Version

**Comment by crston** [comment]
WGBukkit Error.
worldguard error.
