### ISSUE TITLE
/sf <argument>

### ISSUE THREAD

**Issue by arlidencrow** [TheBusyBiscuit/Slimefun4#778]
## Description
every command returns /sf argument  I have had this issue before but it could be resolved by just reinstalling cs-corelib 

## Server Log

C:\Users\John\Desktop\New folder>java -Xmx1G -jar spigot.jar
*** WARNING: This is a development build. It is not meant for production server usage! Please keep backups and update frequently.
Loading libraries, please wait...
Loaded 0 recipes
[13:34:24 INFO]: Loaded 0 recipes
[13:34:25 INFO]: Starting minecraft server version 1.13.1
[13:34:25 INFO]: Loading properties
[13:34:25 INFO]: Default game type: SURVIVAL
[13:34:26 INFO]: This server is running CraftBukkit version git-Spigot-500ff5d-7033f18 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[13:34:26 INFO]: Debug logging is disabled
[13:34:26 INFO]: Server Ping Player Sample Count: 12
[13:34:26 INFO]: Using 4 threads for Netty based IO
[13:34:26 INFO]: Generating keypair
[13:34:26 INFO]: Starting Minecraft server on *:25565
[13:34:26 INFO]: Using default channel type
[13:34:38 INFO]: Set PluginClassLoader as parallel capable
[13:34:39 INFO]: [CS-CoreLib] Loading CS-CoreLib vv1.5.18
[13:34:39 INFO]: [Slimefun] Loading Slimefun vDEV
[13:34:39 INFO]: [ProtocolSupport] Loading ProtocolSupport v4.29-dev
[13:34:39 INFO]: [ProtocolSupport] Detected Spigot server implementation type
[13:34:42 INFO]: [ProtocolSupport] Compression level: 3
[13:34:42 INFO]: [ProtocolSupport] Assume 1.5.2 ping delay: 100
[13:34:42 INFO]: [ProtocolSupport] Assume legacy ping delay: 200
[13:34:42 INFO]: [ProtocolSupport] Login threads keep alive time: 60
[13:34:42 INFO]: [ProtocolSupport] Status threads max count: 2, keep alive time: 60
[13:34:42 INFO]: [ProtocolSupport] Enabling ProtocolSupport v4.29-dev
[13:34:42 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[13:34:42 INFO]: Preparing level "world"
[13:34:43 INFO]: Reloading ResourceManager: Default, bukkit
[13:34:45 INFO]: Loaded 524 recipes
[13:34:46 INFO]: -------- World Settings For [world] --------
[13:34:46 INFO]: Experience Merge Radius: 3.0
[13:34:46 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:34:46 INFO]: Zombie Aggressive Towards Villager: true
[13:34:46 INFO]: Arrow Despawn Rate: 1200
[13:34:46 INFO]: View Distance: 10
[13:34:46 INFO]: Mob Spawn Range: 6
[13:34:46 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:34:46 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[13:34:46 INFO]: Random Lighting Updates: false
[13:34:46 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:34:46 INFO]: Cactus Growth Modifier: 100%
[13:34:46 INFO]: Cane Growth Modifier: 100%
[13:34:46 INFO]: Melon Growth Modifier: 100%
[13:34:46 INFO]: Mushroom Growth Modifier: 100%
[13:34:46 INFO]: Pumpkin Growth Modifier: 100%
[13:34:46 INFO]: Sapling Growth Modifier: 100%
[13:34:46 INFO]: Wheat Growth Modifier: 100%
[13:34:46 INFO]: NetherWart Growth Modifier: 100%
[13:34:46 INFO]: Vine Growth Modifier: 100%
[13:34:46 INFO]: Cocoa Growth Modifier: 100%
[13:34:46 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:34:46 INFO]: Max TNT Explosions: 100
[13:34:46 INFO]: Item Despawn Rate: 6000
[13:34:46 INFO]: Item Merge Radius: 2.5
[13:34:46 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:34:46 INFO]: Nerfing mobs spawned from spawners: false
[13:34:47 INFO]: -------- World Settings For [world_nether] --------
[13:34:47 INFO]: Experience Merge Radius: 3.0
[13:34:47 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:34:47 INFO]: Zombie Aggressive Towards Villager: true
[13:34:47 INFO]: Arrow Despawn Rate: 1200
[13:34:47 INFO]: View Distance: 10
[13:34:47 INFO]: Mob Spawn Range: 6
[13:34:47 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:34:47 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[13:34:47 INFO]: Random Lighting Updates: false
[13:34:47 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:34:47 INFO]: Cactus Growth Modifier: 100%
[13:34:47 INFO]: Cane Growth Modifier: 100%
[13:34:47 INFO]: Melon Growth Modifier: 100%
[13:34:47 INFO]: Mushroom Growth Modifier: 100%
[13:34:47 INFO]: Pumpkin Growth Modifier: 100%
[13:34:47 INFO]: Sapling Growth Modifier: 100%
[13:34:47 INFO]: Wheat Growth Modifier: 100%
[13:34:47 INFO]: NetherWart Growth Modifier: 100%
[13:34:47 INFO]: Vine Growth Modifier: 100%
[13:34:47 INFO]: Cocoa Growth Modifier: 100%
[13:34:47 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:34:47 INFO]: Max TNT Explosions: 100
[13:34:47 INFO]: Item Despawn Rate: 6000
[13:34:47 INFO]: Item Merge Radius: 2.5
[13:34:47 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:34:47 INFO]: Nerfing mobs spawned from spawners: false
[13:34:47 INFO]: -------- World Settings For [world_the_end] --------
[13:34:47 INFO]: Experience Merge Radius: 3.0
[13:34:47 INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:34:47 INFO]: Zombie Aggressive Towards Villager: true
[13:34:47 INFO]: Arrow Despawn Rate: 1200
[13:34:47 INFO]: View Distance: 10
[13:34:47 INFO]: Mob Spawn Range: 6
[13:34:47 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:34:47 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[13:34:47 INFO]: Random Lighting Updates: false
[13:34:47 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:34:47 INFO]: Cactus Growth Modifier: 100%
[13:34:47 INFO]: Cane Growth Modifier: 100%
[13:34:47 INFO]: Melon Growth Modifier: 100%
[13:34:47 INFO]: Mushroom Growth Modifier: 100%
[13:34:47 INFO]: Pumpkin Growth Modifier: 100%
[13:34:47 INFO]: Sapling Growth Modifier: 100%
[13:34:47 INFO]: Wheat Growth Modifier: 100%
[13:34:47 INFO]: NetherWart Growth Modifier: 100%
[13:34:47 INFO]: Vine Growth Modifier: 100%
[13:34:47 INFO]: Cocoa Growth Modifier: 100%
[13:34:47 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:34:47 INFO]: Max TNT Explosions: 100
[13:34:47 INFO]: Item Despawn Rate: 6000
[13:34:47 INFO]: Item Merge Radius: 2.5
[13:34:47 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:34:47 INFO]: Nerfing mobs spawned from spawners: false
[13:34:47 INFO]: Preparing start region for level minecraft:the_nether (Seed: 6596963153369934092)
[13:34:47 INFO]: Preparing spawn area: 4%
[13:34:47 INFO]: Preparing spawn area: 8%
[13:34:47 INFO]: Preparing spawn area: 12%
[13:34:47 INFO]: Preparing spawn area: 16%
[13:34:47 INFO]: Preparing spawn area: 20%
[13:34:47 INFO]: Preparing spawn area: 24%
[13:34:48 INFO]: Preparing spawn area: 28%
[13:34:48 INFO]: Preparing spawn area: 32%
[13:34:48 INFO]: Preparing spawn area: 36%
[13:34:48 INFO]: Preparing spawn area: 40%
[13:34:48 INFO]: Preparing spawn area: 44%
[13:34:48 INFO]: Preparing spawn area: 48%
[13:34:48 INFO]: Preparing spawn area: 52%
[13:34:48 INFO]: Preparing spawn area: 56%
[13:34:48 INFO]: Preparing spawn area: 60%
[13:34:48 INFO]: Preparing spawn area: 64%
[13:34:48 INFO]: Preparing spawn area: 68%
[13:34:48 INFO]: Preparing spawn area: 72%
[13:34:49 INFO]: Preparing spawn area: 76%
[13:34:49 INFO]: Preparing spawn area: 80%
[13:34:49 INFO]: Preparing spawn area: 84%
[13:34:49 INFO]: Preparing spawn area: 88%
[13:34:49 INFO]: Preparing spawn area: 92%
[13:34:49 INFO]: Preparing spawn area: 96%
[13:34:49 INFO]: Preparing spawn area: 100%
[13:34:49 INFO]: Preparing start region for level minecraft:the_end (Seed: 6596963153369934092)
[13:34:49 INFO]: Preparing spawn area: 4%
[13:34:49 INFO]: Preparing spawn area: 8%
[13:34:49 INFO]: Preparing spawn area: 12%
[13:34:49 INFO]: Preparing spawn area: 16%
[13:34:49 INFO]: Preparing spawn area: 20%
[13:34:49 INFO]: Preparing spawn area: 24%
[13:34:49 INFO]: Preparing spawn area: 28%
[13:34:49 INFO]: Preparing spawn area: 32%
[13:34:49 INFO]: Preparing spawn area: 36%
[13:34:49 INFO]: Preparing spawn area: 40%
[13:34:49 INFO]: Preparing spawn area: 44%
[13:34:49 INFO]: Preparing spawn area: 48%
[13:34:49 INFO]: Preparing spawn area: 52%
[13:34:50 INFO]: Preparing spawn area: 56%
[13:34:50 INFO]: Preparing spawn area: 60%
[13:34:50 INFO]: Preparing spawn area: 64%
[13:34:50 INFO]: Preparing spawn area: 68%
[13:34:50 INFO]: Preparing spawn area: 72%
[13:34:50 INFO]: Preparing spawn area: 76%
[13:34:50 INFO]: Preparing spawn area: 80%
[13:34:50 INFO]: Preparing spawn area: 84%
[13:34:50 INFO]: Preparing spawn area: 88%
[13:34:50 INFO]: Preparing spawn area: 92%
[13:34:50 INFO]: Preparing spawn area: 96%
[13:34:50 INFO]: Preparing spawn area: 100%
[13:34:50 INFO]: Preparing start region for level minecraft:overworld (Seed: 6596963153369934092)
[13:34:51 INFO]: Preparing spawn area: 4%
[13:34:51 INFO]: Preparing spawn area: 8%
[13:34:51 INFO]: Preparing spawn area: 12%
[13:34:51 INFO]: Preparing spawn area: 16%
[13:34:51 INFO]: Preparing spawn area: 20%
[13:34:51 INFO]: Preparing spawn area: 24%
[13:34:51 INFO]: Preparing spawn area: 28%
[13:34:52 INFO]: Preparing spawn area: 32%
[13:34:52 INFO]: Preparing spawn area: 36%
[13:34:52 INFO]: Preparing spawn area: 40%
[13:34:52 INFO]: Preparing spawn area: 44%
[13:34:52 INFO]: Preparing spawn area: 48%
[13:34:52 INFO]: Preparing spawn area: 52%
[13:34:52 INFO]: Preparing spawn area: 56%
[13:34:52 INFO]: Preparing spawn area: 60%
[13:34:52 INFO]: Preparing spawn area: 64%
[13:34:52 INFO]: Preparing spawn area: 68%
[13:34:52 INFO]: Preparing spawn area: 72%
[13:34:53 INFO]: Preparing spawn area: 76%
[13:34:53 INFO]: Preparing spawn area: 80%
[13:34:53 INFO]: Preparing spawn area: 84%
[13:34:53 INFO]: Preparing spawn area: 88%
[13:34:53 INFO]: Preparing spawn area: 92%
[13:34:54 INFO]: Preparing spawn area: 96%
[13:34:54 INFO]: Preparing spawn area: 100%
[13:34:54 INFO]: Time elapsed: 6929 ms
[13:34:54 INFO]: [CS-CoreLib] Enabling CS-CoreLib vv1.5.18
[13:34:54 INFO]: [Slimefun] Enabling Slimefun vDEV
[13:34:54 INFO]: [Slimefun] Loading Files...
[13:34:54 WARN]: ###############################################
[13:34:54 WARN]: ############## = -  INFO  - = #################
[13:34:54 WARN]: ###############################################
[13:34:54 WARN]:
[13:34:54 WARN]: Slimefun Warning:
[13:34:54 WARN]:
[13:34:54 WARN]: Slimefun has detected that your Files are either
[13:34:54 WARN]: outdated or do not exist. We generated new Files
[13:34:54 WARN]: instead otherwise Slimefun would not work. If you
[13:34:54 WARN]: have used Slimefun before, your Settings are now
[13:34:54 WARN]: gone. But therefore Slimefun works!
[13:34:54 INFO]: [Slimefun] Loading Config...
[13:34:54 INFO]: [Slimefun] Loading Items...
[13:35:02 ERROR]: Error occurred while enabling Slimefun vDEV (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/compatibility/MaterialHelper
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.machines.ElectrifiedCrucible.registerDefaultRecipes(ElectrifiedCrucible.java:21) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer.<init>(AContainer.java:104) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.machines.ElectrifiedCrucible.<init>(ElectrifiedCrucible.java:14) ~[?:?]
        at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$65.<init>(SlimefunSetup.java:3702) ~[?:?]
        at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup.setupItems(SlimefunSetup.java:3701) ~[?:?]
        at me.mrCookieSlime.Slimefun.SlimefunStartup.onEnable(SlimefunStartup.java:171) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-500ff5d-7033f18]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:428) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:342) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-500ff5d-7033f18]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
**Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.CSCoreLibPlugin.compatibility.MaterialHelper**
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot.jar:git-Spigot-500ff5d-7033f18]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-500ff5d-7033f18]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 17 more
[13:35:02 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:35:02 INFO]: Done (19.650s)! For help, type "help"
[13:35:07 WARN]: Exception in thread "Thread-8"
[13:35:07 WARN]: java.lang.NumberFormatException: For input string: ""
[13:35:07 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[13:35:07 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[13:35:07 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[13:35:07 WARN]:        at me.mrCookieSlime.CSCoreLibPlugin.updater.Updater$UpdaterTask.check(Updater.java:107)
[13:35:07 WARN]:        at me.mrCookieSlime.CSCoreLibPlugin.updater.Updater$UpdaterTask.run(Updater.java:59)
[13:35:07 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:35:07 INFO]: [CS-CoreLib - Updater] CS-CoreLib is up to date!

## Environment (Required)
Minecraft version 1.13.1
spigot version 1.13.1
slime fun version 4-57
cs-corelib 1.5.18

**Comment by arlidencrow** [comment]
ah just need a cs-core lib for 1.13
