### ISSUE TITLE
Please make slimefun compatible with WorldEdit 7

### ISSUE THREAD

**Issue by Towelie** [TheBusyBiscuit/Slimefun4#779]
## Description
Slimefun is not compatible with WorldEdit 7 and errors can be seen in the console due to this (As well as any functionality that is dependent on worldedit not working properly)
A new version of WorldEdit was released for 1.13.x. Any previous worldedit versions no longer work.
Version can be obtained from: http://builds.enginehub.org/job/worldedit?branch=master

## Error
Caused by: java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/WorldEdit/WESlimefunManager$1
        at me.mrCookieSlime.Slimefun.WorldEdit.WESlimefunManager.wrapForLogging(WESlimefunManager.java:24) ~[Slimefun.jar:?]
        at sun.reflect.GeneratedMethodAccessor615.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar:?]
        ... 40 more

## Other Info
CS-Corelib reports similar errors as well.

## Environment
Latest Slimefun & CS_CoreLib versions as of September 6th
Spigot 1.13.1
Linux / Java 8
CentOS 7 x64

**Comment by TheBusyBiscuit** [comment]
No chance of that happening until WorldEdit 7 is available as a maven build.

**Comment by Towelie** [comment]
I remember them always using gradle.
Not a java dev so not sure if that helps https://github.com/sk89q/WorldEdit

Basically, due to that, it's impossible to use Slimefun on 1.13 at the moment without being spammed by errors.
