### ISSUE TITLE
Cannot access input/output cargo node interface

### ISSUE THREAD

**Issue by tanewell** [TheBusyBiscuit/Slimefun4#783]
## Description (Required)
The interface does not open for any of the input or output cargo nodes. The nodes were created using the sf_give command. I get the following error when I attempt to access the nodes.

## Server Log
[14:17:24 ERROR]: Could not pass event ItemUseEvent to Slimefun vDEV - 58 (git 18881806)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.ItemUseListener.onRightClick(ItemUseListener.java:23) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:239) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1240) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-6b015b4-a222e4a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at me.mrCookieSlime.CSCoreLibPlugin.protection.modules.WorldGuardProtectionModule.canAccessChest(WorldGuardProtectionModule.java:19) ~[?:?]
        at me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionManager.canAccessChest(ProtectionManager.java:106) ~[?:?]
        at me.mrCookieSlime.CSCoreLibPlugin.protection.ProtectionManager.canAccessChest(ProtectionManager.java:82) ~[?:?]
        at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.machines.CargoInputNode$1.canOpen(CargoInputNode.java:210) ~[?:?]
        at me.mrCookieSlime.Slimefun.api.inventory.BlockMenu.canOpen(BlockMenu.java:109) ~[?:?]
        at me.mrCookieSlime.Slimefun.listeners.ItemListener.onRightClick(ItemListener.java:253) ~[?:?]
## Evidence / Proof (Required)
No further evidence apart from error log

## Environment (Required)
Minecraft version Spigot 1.13.1 (latest version)
java version "1.8.0_181"
CS-CoreLib-28
Slimefun4-58
Essentials-2.x-SNAPSHOT
EssentialsAntiBuild-2.x-SNAPSHOT
EssentialsProtect-2.x-SNAPSHOT
EssentialsSpawn-2.x-SNAPSHOT
worldedit-bukkit-7.0.0-SNAPSHOT-dist
worldguard-legacy-7.0.0-SNAPSHOT-dist

**Comment by VoidAngel** [comment]
Unfortunately Slimefun (Or CS-Corelib to be more exact) is not integrated with WorldGuard 7 yet. You will have to wait until WG 7 is officially released most likely. If you know someone that can update it for you specifically that might be the faster option.

**Comment by tanewell** [comment]
Thank you. Removing WorldGuard resolved my issue.

**Comment by xH3LLRAIZ3Rx** [comment]
Actually WorldGuard 7 is in beta I think now, so adding it should be fine.

**Comment by xH3LLRAIZ3Rx** [comment]
I went ahead and made a issue with the updated WG7 code on Cs-CoreLib
