### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SouirTommer** [TheBusyBiscuit/Slimefun4#792]
## Description (Required)
i have this error and i dont know how to fix it.

## Server Log
[12:40:20] [Craft Scheduler Thread - 109/WARN]: [CS-CoreLib] Plugin CS-CoreLib vv1.5.18 generated an exception while executing task 59
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.Metrics.postPlugin(Metrics.java:335) ~[?:?]
        at org.mcstats.Metrics.access$400(Metrics.java:57) ~[?:?]
        at org.mcstats.Metrics$1.run(Metrics.java:223) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0]

[12:40:20] [Craft Scheduler Thread - 114/WARN]: [ExoticGarden] Plugin ExoticGarden v1.6.3 generated an exception while executing task 195
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.Metrics.postPlugin(Metrics.java:335) ~[?:?]
        at org.mcstats.Metrics.access$400(Metrics.java:57) ~[?:?]
        at org.mcstats.Metrics$1.run(Metrics.java:223) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0]

[12:40:20] [Craft Scheduler Thread - 112/WARN]: [Slimefun] Plugin Slimefun vv4.1.15 generated an exception while executing task 172
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.Metrics.postPlugin(Metrics.java:335) ~[?:?]
        at org.mcstats.Metrics.access$400(Metrics.java:57) ~[?:?]
        at org.mcstats.Metrics$1.run(Metrics.java:223) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0]

[12:40:20] [Craft Scheduler Thread - 115/WARN]: [SlimeXpansion] Plugin SlimeXpansion v1.1.9 generated an exception while executing task 205
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.Metrics.postPlugin(Metrics.java:335) ~[?:?]
        at org.mcstats.Metrics.access$400(Metrics.java:57) ~[?:?]
        at org.mcstats.Metrics$1.run(Metrics.java:223) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0]

## Evidence / Proof (Required)

Environment (Required)
spigot 1.12.2
CS-CoreLib vv1.5.18
Slimefun vv4.1.15
ExtraGear v1.1.1
ExoticGarden v1.6.3
TinkerTools v2.1.0
SlimeXpansion v1.1.9
ExtraHeads v1.0

**Comment by TheBusyBiscuit** [comment]
This is not related to Slimefun, the error comes from CS-CoreLib but the actual problem is caused by a ambiguity issue in your server software.
That's all I can say about that, maybe try updating spigot?
