### ISSUE TITLE
Furnace Bug and Items all unlocked

### ISSUE THREAD

**Issue by Meta-Win** [TheBusyBiscuit/Slimefun4#794]
(Bad English)
**1º:** Slimefun Guide comes with all items already unlocked.
![itemsunlocked](https://user-images.githubusercontent.com/33970831/46635585-5717a600-cb2b-11e8-95c6-5068a1277385.jpg)

**2º:** Furnace Bug. Furnace stop items from cooking and duplicate parts of the GUI.
![wqournw 1](https://user-images.githubusercontent.com/33970831/46635725-c097b480-cb2b-11e8-8ffb-816debe73f71.png)

Furnace Log:

> [18:49:01] [Server thread/ERROR]: Could not pass event FurnaceSmeltEvent to Slimefun vDEV - 58 (git 18881806)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-f6a273b-1ceee63]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f6a273b-1ceee63]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at net.minecraft.server.v1_13_R2.TileEntityFurnace.burn(TileEntityFurnace.java:362) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at net.minecraft.server.v1_13_R2.TileEntityFurnace.Y_(TileEntityFurnace.java:308) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1247) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:601) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:972) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-1ceee63]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.NullPointerException
	at me.mrCookieSlime.Slimefun.listeners.FurnaceListener.onSmelt(FurnaceListener.java:42) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-f6a273b-1ceee63]
	... 12 more

**EDIT:**
**3º:** Portable Crafter can be placed on the ground.
![2018-10-08_23 24 57](https://user-images.githubusercontent.com/33970831/46643319-f485d080-cb51-11e8-9454-402a7af82719.png)

**Versions:**
spigot-1.13.1
CS-CoreLib-29
Slimefun4-58

**Comment by xH3LLRAIZ3Rx** [comment]
Same problem, actually all the right click slimefun items don't seem to work at all with no errors

**Comment by Sniddunc** [comment]
I made a pull request to fix this. The issue is that the Furnace was surpassing it's needed cooktime. This was causing it to create the weird GUI bug shown above. #810

**Comment by PrzemoVi** [comment]
Use my modified .jars (both cscorelib and slimefun):
https://drive.google.com/open?id=16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5

Fixed worldedit 7 (my request #814)
Fixed enchanted furnaces and lumber axe duplication glitch (#810)
Fixed auto, portable crafting. table, electric furnace and charging bench (my request TheBusyBiscuit/CS-CoreLib#64)

Warn: This will broke support with worldedit older than 7.0!!!
