### ISSUE TITLE
GPS Error Log - 1.14-RO.1

### ISSUE THREAD

**Issue by Izaic** [TheBusyBiscuit/Slimefun4#907]
Unfortunately I'm not sure when this triggered. I've had multiple issues with Slimefun on 1.14.

Server Software: CraftBukkit
  Build: git-Spigot-1eece4f-a584320 (MC: 1.14)
  Minecraft: 1.14-R0.1-SNAPSHOT

Installed Plugins (5)
  + Brewery 1.7.1
  + SpawnChunks 0.1
  + CS-CoreLib DEV - 39 (git cc6a7de0)
  + AlchemicalArrows 3.1.0
  + Slimefun DEV - 96 (git 3feff223)

Ticked Block:
  World: world
  X: -927
  Y: 176
  Z: -242

Slimefun Data:
  ID: GPS_TRANSMITTER
  Inventory: false
  Data: {"owner":"0beb3547-35d3-4c2e-9de9-8339f2795060","energy-charge":"0","id":"GPS_TRANSMITTER"}

Stacktrace:

java.lang.NullPointerException
	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:194)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

https://gist.github.com/Izaic/cd35ce774dc8a6f7988c88129526532e

**Comment by Loopergodfather** [comment]
I am having the exact same issues.  

https://pastebin.com/7B4MxCnT

**Comment by TheBusyBiscuit** [comment]
There have been more than 40 new builds since this Issue was created.
If it still persists, feel free to open a new issue with an Error-Report from the latest builds.
