### ISSUE TITLE
Energy issues in 1.14

### ISSUE THREAD

**Issue by Izaic** [TheBusyBiscuit/Slimefun4#908]
1: The regulators will show power past the limit of the capacitor
2: Capacitors will not update and show the green bar as they get full

This is a error from one of those problems. I unfortunately can't offer more information as the console is going nuts with slimefun errors and issues, and it's next to impossible to pinpoint what i last did caused what. (Alongside the lovely TPS and chunk issues in 1.14)

Server Software: CraftBukkit
  Build: git-Spigot-1eece4f-a584320 (MC: 1.14)
  Minecraft: 1.14-R0.1-SNAPSHOT

Installed Plugins (5)
  + Brewery 1.7.1
  + SpawnChunks 0.1
  + CS-CoreLib DEV - 39 (git cc6a7de0)
  + AlchemicalArrows 3.1.0
  + Slimefun DEV - 96 (git 3feff223)

Ticked Block:
  World: world
  X: -919
  Y: 176
  Z: -243

Slimefun Data:
  ID: ENERGY_REGULATOR
  Inventory: false
  Data: {"id":"ENERGY_REGULATOR"}

Stacktrace:

java.lang.NullPointerException
	at me.mrCookieSlime.Slimefun.api.energy.EnergyNet.tick(EnergyNet.java:147)
	at me.mrCookieSlime.Slimefun.Setup.SlimefunSetup$48.tick(SlimefunSetup.java:2999)
	at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:191)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

https://gist.github.com/Izaic/cd35ce774dc8a6f7988c88129526532e

**Comment by xH3LLRAIZ3Rx** [comment]
This bug is not happening in 1.14.4
