### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by GrahamovyRozek** [TheBusyBiscuit/Slimefun4#927]
## Description (Required)
Hey idont know what is happening and what exactly is doing it. So ... Dont know if you understand what this mean but i dont :D And sometimes i have another bug when a player uses *PICKAXE_OF_CONTAINMENT* and he mines it just duplicate the pickaxe. Every block he mine it drops PICKAXE_OF_CONTAINMENT :D. Dont have any custom plugin for custom drops or anything like that ... and when it drops the item console dont send any errors ... :D And when you use grapling hook on animal it just destroy it and act like normal lead. That may cause plugin called *revenge* but im okay with it.

## Server Log / Error Report
[14:40:24] [Craft Scheduler Thread - 501/WARN]: [Slimefun] Plugin Slimefun vDEV - 106 (git 63ecc1fb) generated an exception while executing task 83
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_191]
at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_191]
at me.mrCookieSlime.Slimefun.api.TickerTask.run(TickerTask.java:295) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-baafee9-17543ec]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [minecraft_server.jar:git-Spigot-baafee9-17543ec]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

 - Minecraft Version: 1.14.2-R0.1-SNAPSHOT
 - Slimefun Version: v106 
 - CS-CoreLib Version: v50

**Comment by GrahamovyRozek** [comment]
Fixed :D
