### ISSUE TITLE
 Slimefun vv4.1.15 generated an exception  java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/general/Particles/MC_1_8/ParticleEffect

### ISSUE THREAD

**Issue by LightYugen** [TheBusyBiscuit/Slimefun4#936]
How to fix this error:
```

[Slimefun] Task #167545 for Slimefun vv4.1.15 generated an exception

java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/general/Particles/MC_1_8/ParticleEffect

at me.mrCookieSlime.Slimefun.AncientAltar.RitualAnimation.idle(RitualAnimation.java:64) ~[?:?]

at me.mrCookieSlime.Slimefun.AncientAltar.RitualAnimation.run(RitualAnimation.java:50) ~[?:?]

at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by TheBusyBiscuit** [comment]
You need to update Slimefun or downgrade CS-CoreLib...

Also, your ticket will not be accepted if you don't follow the template...

**Comment by LightYugen** [comment]
sorry, @TheBusyBiscuit , i use spigot 1.12.2, what do you suggest i do and which versions should i upgrade or downgrade to?

**Comment by TheBusyBiscuit** [comment]
Build 33 of CS-CoreLib might work
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/#33
