### ISSUE TITLE
Slimefun is spamming my console

### ISSUE THREAD

**Issue by Cyanoure** [TheBusyBiscuit/Slimefun4#946]
## Description (Required)
Slimefun is spamming my console very much.
I don't know what does this.

## Steps to reproduce the Issue (Required)
-Starting my server
-After the server start up the spamming is starts
![image](https://user-images.githubusercontent.com/30216303/59968185-d7edc500-9535-11e9-8322-ee772d248e40.png)

## Expected behavior (Required)
Please don't spam my console.

## Server Log / Error Report

> [21:23:19 WARN]: [Slimefun] Task #337464 for Slimefun vv4.1.15 generated an exception
java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/general/Particles/MC_1_8/ParticleEffect
        at me.mrCookieSlime.Slimefun.api.network.Network$1.run(Network.java:162) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[serverfile.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [serverfile.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [serverfile.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [serverfile.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [serverfile.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [serverfile.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

## Environment (Required)

 - Minecraft Version: 1.12.2
 - Slimefun Version: 4.1.15
 - CS-CoreLib Version: 1.6.1

**Comment by TheBusyBiscuit** [comment]
Your CS-CoreLib Version is incompatible with your Slimefun Version.

Either update Minecraft, Slimefun and CS-CoreLib, or downgrade CS-CoreLib.
Build 33 might work
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/#33

**Comment by Cyanoure** [comment]
Thank you
